[package]
name = "repository"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-postgres = { workspace = true }
async-trait = "0.1"
thiserror = { workspace = true }
chrono = { workspace = true }
model = { path = "../model" }
