global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'shoppingcart-app'
    static_configs:
      - targets: [ 'app:8081' ]    # Порт приложения, где экспонируется /metrics

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]