groups:
  - name: example_alert_rules
    rules:
      - alert: HighErrorRate
        expr: increase(http_requests_total{status=~"5.."}[1m]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "More than 5 5xx errors in the last minute."