[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tokio-postgres = { workspace = true }
deadpool-postgres = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
app_config = { workspace = true }
